apiVersion: skaffold/v1
kind: Config
metadata:
  name: gcp-cloud-native-stack
build:
  artifacts:
  - image: catalog
    context: catalog
  - image: frontend
    context: frontend
  - image: recommendation
    context: recommendation
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**.yaml
